source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/someweardev/somewear-specs.git'

platform :ios, '10.0'
use_frameworks!

target 'HelloSpace' do

#  pod 'Somewear'
  pod 'Somewear', :path => '..'
end
